### ISSUE TITLE
Plugin Directory: Plugin rating bar is underlined on hover

### ISSUE THREAD

**Issue by ndiego** [WordPress/wordpress.org#242]
I think only the number of ratings should be underlined on hover, but the whole bar is underlined as well. More clear in the gif below.

![rate-bar-hover](https://github.com/WordPress/wordpress.org/assets/4832319/19dcde41-feda-4709-b97e-a38d277699dc)

**Comment by StevenDufresne** [comment]
Fixed in https://meta.trac.wordpress.org/changeset/13516.

I decided to remove the underline that looks broken but not rebuild the component hover interaction state.

<img width="253" alt="Screenshot 2024-04-15 at 11 33 54 AM" src="https://github.com/WordPress/wordpress.org/assets/1657336/316f50d2-8fd9-434d-b29c-4a6f71d7c473">
