### ISSUE TITLE
Support forums: Reconsider the color of visited links

### ISSUE THREAD

**Issue by ndiego** [WordPress/wordpress.org#248]
The visited links in the new support forums design are purple. I find this to be a bit distracting. The old design used a slightly different blue color.

| New design | Old design |
|-|-|
|<img width="1334" alt="image" src="https://github.com/WordPress/wordpress.org/assets/4832319/32463445-4b13-42d5-888b-f469d0de50c4">|<img width="1333" alt="image" src="https://github.com/WordPress/wordpress.org/assets/4832319/130fdb78-6441-429c-ad31-9d2dfbda6621">|

Thoughts @WordPress/meta-design?

**Comment by StevenDufresne** [comment]
I agree. Can we do lighter blue?

<img width="319" alt="Screenshot 2024-04-15 at 11 41 41 AM" src="https://github.com/WordPress/wordpress.org/assets/1657336/a70c0853-9be1-4dd5-a126-027240eb40a3">

**Comment by jasmussen** [comment]
Happy to change from the purple. Question though: light blueberry is right there for the taking. But it's not clear to me what contrast ratio visited links should meet for AA. The current light blueberry doesn't meet that ratio, and the lightest blueberry that would is #4967FD. Here's a comparison:

![lighter blueberry vs blueberry](https://github.com/WordPress/wordpress.org/assets/1204802/7909cfd6-4e1d-4b8b-8af7-3ef0557fa016)

That's the lighter blueberry on the left, and the default blueberry for links on the right.

**Comment by ndiego** [comment]
I hesitate to ask this question, but do we need a visited link color? I don't believe we have this on other sites like [Developer Resources](https://developer.wordpress.org/block-editor), [Developer Blog](https://developer.wordpress.org/news/), [Showcase](https://wordpress.org/showcase/), etc.

**Comment by StevenDufresne** [comment]
Good question. I see the value of it in the support forum table but maybe not valuable anywhere else.

**Comment by jasmussen** [comment]
I wonder, @macmanx2 what are your instincts here?

**Comment by macmanx2** [comment]
We need it in the forums, as it's an important part of moderator workflows. It's the only way we can keep track of which threads we've seen.

More details from more folks under the original Meta ticket: https://meta.trac.wordpress.org/ticket/7529

**Comment by ndiego** [comment]
> We need it in the forums, as it's an important part of moderator workflows. It's the only way we can keep track of which threads we've seen.

Thanks for the context @macmanx2!

**Comment by adamwoodnz** [comment]
> The current light blueberry doesn't meet that ratio, and the lightest blueberry that would is #4967FD.

I've tried this color, and the difference is so subtle I almost can't tell (I have visited the second and third topics):

![Image](https://github.com/WordPress/wordpress.org/assets/1017872/3343f705-c1d3-453c-9920-8229a2f2c6d8)

**Comment by macmanx2** [comment]
Yeah, I'd take purple over that, please. :)

IDK if you're looking for something non-purple, how about a lighter gray, of the 777 or 555 variety? It would be more inline with the colors than purple, but it would make it difficult to distinguish from closed/locked threads, though I think that's a better tradeoff than difficulty distinguishing between new and visited links.

**Comment by adamwoodnz** [comment]
A couple more options based on the above, which both meet contrast requirements. IMO the grey looks like it could be disabled, but I think it's an improvement. The dark blueberry is still very subtle. Maybe an even darker blueberry could work.

### Screenshots

| Charcoal 4 | Dark Blueberry |
|-|-|
| ![Image](https://github.com/WordPress/wordpress.org/assets/1017872/5e66a97c-98a6-4672-a06a-ef2639a5c203) | ![Image](https://github.com/WordPress/wordpress.org/assets/1017872/ca01d353-3d14-4b38-837f-0720fe3be550) |

**Comment by adamwoodnz** [comment]
Also if this is only really useful to mods, we could only apply it for that role.

**Comment by jasmussen** [comment]
It's very clear this is critical to get right, and I'd be very happy to defer almost entirely to our moderators. To that end I've explored a range of options here.

A word of warning, though: the contrast rules for visited links are not clear to me. Best I can tell visited links do not need to contrast with unvisited links, but [should maintain text contrast with the background](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html). That means some of the light color versions in this mockup fail that test:

<img width="1291" alt="Options" src="https://github.com/WordPress/wordpress.org/assets/1204802/cfffbdb2-0c70-4e67-9d21-fa923d7985e6">

At a glance, it is indeed the very dimmed versions above that seem most appealing if you are moderating a slew of posts and want _clear contrast between what you've seen and what you haven't seen_. But since they fail contrast checks, it puts us in a tricky place. That's why in the above there are some explorations that remove the underline on visited links. That gives good contrast, but is also dubious territory.

Would dotted underlines work? I.e. `text-decoration-style: dotted;`

The final option as outlined, is to show as we do today, a checkmark next to visited links. This would be a `before:` thing, and we could use this unicode glyph: ✓. Best I can tell, that would get us close to what exists in the old theme. Now whether we could apply that in a blanket way across the site, that's less clear, but perhaps we could differentiate here. That would give us this:

<img width="553" alt="Options, across" src="https://github.com/WordPress/wordpress.org/assets/1204802/ffb88b64-cd96-4362-8c7b-d4329109edb7">

What do you think? Thanks for your advice, @macmanx2!

**Comment by ndiego** [comment]
For what it's worth, I like the dark blue color.

**Comment by ryelle** [comment]
Personally, I really like the purple, I like that it's reminiscent of web defaults. The dark purple is also good, it's less bright so maybe less distracting.

The links without underlines would fail accessibility checks for not having a non-color identifying feature, so those would also be out. You could try a different underline style, but that might be distracting too (and an unexpected way to flag visited links, IMO).

Actually, the forum links are already not underlined (probably getting away with this because the UI makes these clearly links). So changing the underline style wouldn't apply here.

I tried a few options in-context, though I had to color-pick to get the colors so they might be off:

| Dark purple | Dark blue | Grey |
|---|---|---|
| <img width="847" alt="dark-purple" src="https://github.com/WordPress/wordpress.org/assets/541093/426258a4-5aa7-4837-a2de-138330f3fc41"> | <img width="854" alt="link-dark-blue" src="https://github.com/WordPress/wordpress.org/assets/541093/e0068a20-8da7-451b-bba3-aac9237a7203"> | <img width="855" alt="link-grey" src="https://github.com/WordPress/wordpress.org/assets/541093/54dfa1ce-a7d5-4b94-a744-bc439af2237a"> |

The grey in that image fails contrast against the light grey row background, so that would also be out. `charcoal-4` would pass though, like @adamwoodnz suggested above.

**Comment by macmanx2** [comment]
As a moderator, I vote for either the dark purple or charcoal 4. There is some bias there, as I've grown used to the purple, maybe charcoal 4 is better.

I do agree that dark blue is the most aesthetically pleasing in a screenshot, but with such a small team and such limited time, fast scrolling is the name of the game for moderators and I can't see it being visually distinctive enough when scrolling.

**Comment by adamwoodnz** [comment]
> ... the purple, I like that it's reminiscent of web defaults. The dark purple is also good, it's less bright so maybe less distracting.

I feel the same.

I'm seeing the most votes for a darker shade, and mostly for dark purple so I'll run with that unless I hear any strong objections. Thanks for the input everyone.

**Comment by adamwoodnz** [comment]
Please let me know the hex for the dark purple @jasmussen, I can't see it in [the .org color palette](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?type=design&node-id=1-2193&mode=dev) yet.

**Comment by jasmussen** [comment]
Here's the dark purple: #5300BE — I also added it to the palette.
