### ISSUE TITLE
Plugins: Plugin card title cuts off with ellipsis

### ISSUE THREAD

**Issue by ryelle** [WordPress/wordpress.org#277]
When browsing the site, I noticed that sometimes the plugin title is cut off with an ellipsis, but there's still room for more of the title. For example, this one is called "UsersWP – Front-end login form, User Registration, User Profile & Members Directory plugin for WordPress", but it cuts off at the `–`

<img width="597" alt="Screenshot 2024-04-23 at 9 52 03 AM" src="https://github.com/WordPress/wordpress.org/assets/541093/bfdfbd51-8135-42ad-a18b-b5fad6674c5e">

Same for this one "Better Messages – Live Chat for WordPress, BuddyPress, PeepSo, Ultimate Member, BuddyBoss"

<img width="588" alt="Screenshot 2024-04-23 at 10 01 36 AM" src="https://github.com/WordPress/wordpress.org/assets/541093/011e7205-f588-4592-bd90-8276d8eea37d">

I would expect to see more of the title before the `…`.

This is on Mac/Firefox, at full desktop size.

Perhaps this isn't an issue if [title guidelines appear to prevent overly long titles](https://meta.trac.wordpress.org/ticket/7577)?

**Comment by ndiego** [comment]
Hmm, I am not seeing this on Chrome/Safari.

**Comment by ryelle** [comment]
Yeah, I don't see it in Safari. It looks like this uses some webkit properties to get the line-clamp working. Putting `display:block` on the link fixes it for me:

<img width="594" alt="Screenshot 2024-04-23 at 2 38 42 PM" src="https://github.com/WordPress/wordpress.org/assets/541093/52756c61-4a63-4ade-8679-ac47e2366804">

**Comment by StevenDufresne** [comment]
I added `display:block;` since it fixes it and it makes logical sense for the element to have that display type.

**Comment by StevenDufresne** [comment]
Adding `display:block;` broke the outline mechanism on links for plugin cards. I've added a temporary underline for plugin cards. It's a bit of a mess because of the ellipsis implementation and some overflow hidden and forced heights. I think it's good enough for now based on the circumstances but the plugin cards should probably be rebuilt at some point.

Edit:
Reference: https://wordpress.slack.com/archives/C02QB8GMM/p1714012269322099
