### ISSUE TITLE
Avoid typographic widows

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wordpress.org#284]
Reported by: @jasmussen

<hr>

There’s a typographic widow here:

![Image](https://github.com/WordPress/wordpress.org/assets/1204802/97fcfb62-859b-4737-b72d-a5b17c37bb1e)

That one is particularly tricky because it's appears responsively. For that reason, the easiest fix is to apply `text-wrap: pretty;` across the entire section. In fact it might be useful to have this applied simply to the paragraph element.

**Comment by StevenDufresne** [comment]
I see this was given priority as "high". The widow currently exists in the current theme.

I would prefer we invest effort in https://github.com/WordPress/wordpress.org/issues/224#issuecomment-2076826111 instead of adding this temporary fix to the new theme.

**Comment by adamwoodnz** [comment]
It should be applied to paragraphs via the parent theme, unless is it's been overridden

https://github.com/WordPress/wporg-parent-2021/blob/trunk/source/wp-content/themes/wporg-parent-2021/sass/base/_elements.scss#L16

**Comment by jasmussen** [comment]
It appears because the text is not a paragraph, it's a div:

![Screenshot 2024-04-29 at 08 31 16](https://github.com/WordPress/wordpress.org/assets/1204802/122185d7-f98f-4e39-b513-8c5127cd3eda)

It's high priority to fix the typographic widow, and the text-wrap property should theoretically have been a generic fix, except for the paragraph thing. I would agree it can be fixed either by moving to the new default CTA style. Another option, potentially, is to edit the content of the widgets to add the `<p>` tags manually.
