### ISSUE TITLE
Forums: provide explanation to user when/if posts are shadow deleted

### ISSUE THREAD

**Issue by bozzmedia** [WordPress/wordpress.org#302]
On occasion a post is removed without explanation and without a trace of the original post. Without getting into a debate on the merits of when a post is useful / why it is removed, receiving a message/email/notification (edit: on forums website itself) that explains what happened would be helpful besides the current practice of vaporizing the post with no explanation.

**Comment by macmanx2** [comment]
Threads and replies on the WordPress.org forum are only ever removed for violations of the Guidelines https://wordpress.org/support/guidelines/ or, on rare request, for valid legal, security, or personal safety reasons.

Almost all the time, a reply from a moderator will at-mention the removed poster before it is deleted. This will send an email with the moderator's message to the email address on the poster's WordPress.org profile.

Mistakes do happen from time to time, and you can reach the moderators following these steps: https://wordpress.org/support/guidelines/#contacting-the-moderators

**Comment by bozzmedia** [comment]
> Almost all the time, a reply from a moderator will at-mention the removed poster before it is deleted. This will send an email with the moderator's message to the email address on the poster's WordPress.org profile.

This used to be the case, but in the last year or so I've noticed that doesn't tend to happen. The post (often a reply not an original post) is just vaporized and can not be found, no reply or explanation given. Understood that level of transparency is not a priority for the forums, thanks for the reply.

**Comment by macmanx2** [comment]
I am a moderator and can confirm that we still notify when deleting.

I'd rather not turn this into a your-word-vs-mine thing in this venue though, since it's not the right place for it.

As mentioned, mistakes do happen from time to time, and you can reach the moderators following these steps: https://wordpress.org/support/guidelines/#contacting-the-moderators

This will be my last comment here, as the issue has been closed.

**Comment by bozzmedia** [comment]
Fair enough. I would look up recent issues with this but I can't find the posts because they are gone, so I can't bring anything to the mod team. This was the intent of my request: have a feature where the post is removed publicly but an explanation given within the forums itself. It also sounds like the user needs to be subscribed to new replies to get this notification if I understand correctly. Not the best transparency/UX but understood, not a priority.

**Comment by macmanx2** [comment]
Sorry, it's me again, gotta clear up the misinformation.

A forum user does not need to be subscribed to new replies to get these notifications. As mentioned, "a reply from a moderator will at-mention the removed poster before it is deleted."

When a forum user is at-mentioned, they receive an email to the address on the forum profile, whether they are subscribed or not. That's how the mention system works across all of the forums, and that's why we use it when leaving an explanation for why something has been deleted. If it's not in your email's inbox, it could be in the spam folder.

But, again, mistakes do happen from time to time, and you can reach the moderators following these steps: https://wordpress.org/support/guidelines/#contacting-the-moderators

So, to close this out, we already have a practice in place to notify when things are deleted. Indeed it could be a built-out automated system, and one is being discussed from time to time, but it is currently not a priority across the project's available developers.

**Comment by bozzmedia** [comment]
> So, to close this out, we already have a practice in place to notify when things are deleted. Indeed it could be a built-out automated system, and one is being discussed from time to time, but it is currently not a priority across the project's available developers.

Without a way to look up these removed posts, or the replies to them, I can't find the mentions, or the messages in my inbox. I receive other forum messages fine. It's not ideal for a number of reasons for the end user and why I was suggesting this idea. Glad to hear that it is occasionally discussed and considered, thanks for your time.
