### ISSUE TITLE
Plugins: Add "Community" and "Commercial" descriptions to search archives

### ISSUE THREAD

**Issue by ndiego** [WordPress/wordpress.org#308]
Since the most recent refresh, there has been some discussion around the "Community" and "Commercial" categories. While these categories have been in place for [quite some time](https://make.wordpress.org/plugins/2022/12/16/plugins-themes-categorization/), what stood out to me is that while there are descriptions on the category archives, there is no description on the search archive when you filter by either term. 

I think adding the descriptions to the search archives when either term is selected would be helpful.

| Category archives | Search archive + selecting a term | Proposed (needs design help) |
|-|-|-|
|<img width="1545" alt="image" src="https://github.com/WordPress/wordpress.org/assets/4832319/7753c9a2-1966-4d67-acc3-1aa3040a7741">|<img width="1548" alt="image" src="https://github.com/WordPress/wordpress.org/assets/4832319/77a3f838-a2cf-4d07-bf76-ddeb6c2634f6">|<img width="1551" alt="image" src="https://github.com/WordPress/wordpress.org/assets/4832319/eb5ba800-ea76-4ab4-bf88-4ebf261cad3d">|

**Comment by ndiego** [comment]
My proposed mockup needs some design help, but what do you think of this approach @WordPress/meta-design?

**Comment by jasmussen** [comment]
Could it be `Community results for "blocks"`? It's notably this double heading that looks awkward:

![Screenshot 2024-05-07 at 16 19 45](https://github.com/WordPress/wordpress.org/assets/1204802/c03d166f-719f-4f98-aad9-9c9fec063c25)

The gray help text can sit under the heading per usual, if that's helpful.

**Comment by ndiego** [comment]
> Could it be Community results for "blocks"? 

Yeah I think that could work nicely.

> It's notably this double heading that looks awkward:
> The gray help text can sit under the heading per usual, if that's helpful.

Agreed on both.

**Comment by fcoveram** [comment]
I don't see the reason for adding the `Search results for: "blocks"` part. Regardless of supporting the idea, and previously sharing a mockup for it, it currently does not exist in the other sections.

With that in mind, and in sync with #309, I would remove that text, place all search actions in one row, and include the category description.

Here is a mockup gathering the three changes mentioned.

![Mockup of Plugins search results](https://github.com/WordPress/wordpress.org/assets/895819/cc21c19b-f775-4464-b54a-21a69f62bcb9)

**Comment by ndiego** [comment]
> I don't see the reason for adding the Search results for: "blocks" part.

That's the title (`<h1>`) on the page. It probably needs to be there for SEO/accessibility, but I am not an expert.

**Comment by fcoveram** [comment]
So in that vein, do we need to update the all search results pages? If so, I then would like to go back to the idea shared previously that adds a sentence above the results grid.

**Comment by ryelle** [comment]
> That's the title (`<h1>`) on the page. It probably needs to be there for SEO/accessibility, but I am not an expert.

That's correct, but technically we can hide it with the `screen-reader-text` class as long as it's clear to sighted users what the current page context is. For example, on patterns we have this on all archives, but we can hide it because the breadcrumbs give context + the item is selected in the menu.

| Archive | Search results |
|---|---|
| <img width="1627" alt="Screenshot 2024-05-08 at 10 28 44 AM" src="https://github.com/WordPress/wordpress.org/assets/541093/823e9654-7d2c-40b9-8a0b-775208873133"> | <img width="1553" alt="Screenshot 2024-05-08 at 10 34 00 AM" src="https://github.com/WordPress/wordpress.org/assets/541093/97c5d22f-e1e1-4bdc-a41e-ca5cb3767fe8"> |

**Comment by ndiego** [comment]
> That's correct, but technically we can hide it with the screen-reader-text class as long as it's clear to sighted users what the current page context is. For example, on patterns we have this on all archives, but we can hide it because the breadcrumbs give context + the item is selected in the menu.

Based on this, I like your mockup @fcoveram. 👇 

![Mockup of Plugins search results](https://github.com/WordPress/wordpress.org/assets/895819/cc21c19b-f775-4464-b54a-21a69f62bcb9)

@StevenDufresne thoughts on moving forward with this iteration? Note this mockup does include the proposed changes in #309

**Comment by ryelle** [comment]
The proper heading for a search results page should be "Search results" or "Search results for [term]", though. The production site is doing this correctly, now. Otherwise this has the same `h1` as the main "Community" archive. And there can only be one `h1` here, so the invisible heading doesn't apply, as there's already one visible `h1`.

Maybe the headings can be combined to be "Community plugins: Search results for [term]" with the description under it?

**Comment by ndiego** [comment]
Could "Community plugins" be an `h2` like the headings (that look the same) on the Homepage?

**Comment by ryelle** [comment]
I suppose (technically nothing wrong with it), but I feel like you're loosing half the context either way. Instead of only saying search results like production does now, it'll only (appear to) say "community plugins" — only screen reader users will get the benefit of full context.

IMO it works on Patterns because there is no heading, so you look to the filters & breadcrumbs. Here, there is a heading, but it's not the full story, so it feels just as strange as the original issue. But this isn't a strong opinion, so feel free to outvote me.

**Comment by ndiego** [comment]
I think "Community plugins: Search results for [term]" could work well too. No stong opinions here either

**Comment by StevenDufresne** [comment]
For me, this is the same conversion we are having in https://github.com/WordPress/wporg-mu-plugins/discussions/603 and it should be solved consistently across patterns/plugins/themes. 

I feel like we can do category education with a tooltip (assuming we can make it accessible). 


<img width="1132" alt="Group 1 (18)" src="https://github.com/WordPress/wordpress.org/assets/1657336/886e5954-2439-4833-8db6-64331dd9b464">

**Comment by ndiego** [comment]
> I feel like we can do category education with a tooltip (assuming we can make it accessible).

That's a cool idea!

**Comment by StevenDufresne** [comment]
@fcoveram Do you have any thoughts on [this idea](https://github.com/WordPress/wordpress.org/issues/308#issuecomment-2101813142)?

**Comment by fcoveram** [comment]
I like the idea. Do you have an idea for the "Learn more" link? I don't think we need it.

**Comment by ndiego** [comment]
> I like the idea. Do you have an idea for the "Learn more" link? I don't think we need it.

The only place I can think to link to is the [Make post](https://make.wordpress.org/meta/2023/06/13/new-filter-controls-discover-commercial-and-community-in-the-theme-and-plugin-directory/) 🤔  I am surprised there is no information (that I could find) in the [WordPress.org Plugin Directory](https://developer.wordpress.org/plugins/wordpress-org/) section of the Plugin Handbook.

**Comment by StevenDufresne** [comment]
We could exclude it from the first iteration but I think it's valuable to have a place for plugins to visit that explains the categorizations along with how to categorize their plugin in the future.

**Comment by ndiego** [comment]
As a first step, I would love to see something like this when "test" is searched for: 

| Search for all | Search for community | Search for commercial |
|-|-|-|
|<img width="909" alt="image" src="https://github.com/WordPress/wordpress.org/assets/4832319/ea133b2e-d553-442d-882a-13009e8a9fcd">|<img width="908" alt="image" src="https://github.com/WordPress/wordpress.org/assets/4832319/186ad20d-02d8-49ea-816c-539c7ac580f9">|<img width="908" alt="image" src="https://github.com/WordPress/wordpress.org/assets/4832319/70892d06-8f79-403c-98e7-2e1c2ea55088">|

This is similar to what is being done in the Patterns Directory. It doesn't solve all issues, but does provide more context to the search and should be easy to implement.

**Comment by jasmussen** [comment]
That feels a great start to build on, and is hopefully easy to do.

**Comment by fcoveram** [comment]
@ndiego's idea looks good. +1 to go with that.
