### ISSUE TITLE
Breadcrumb: No way to get home.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wordpress.org#405]
If I'm on a team page, There isn't a link to get back to the make homepage.

Link: https://make.wordpress.org/design/

## Screenshots
![Image](https://github.com/user-attachments/assets/b4442fad-5a30-410b-bcb9-b4257a8e37ec)

**Comment by adamwoodnz** [comment]
I'm not sure if this is a commonly used navigation route. @WordPress/meta-design what are your thoughts please?

**Comment by StevenDufresne** [comment]
Almost all of our subnavs link back to home.

[Forums](https://wordpress.org/support/forum/installation/)
[Developers](https://developer.wordpress.org/block-editor/)
[Showcase](https://wordpress.org/showcase/nasa/)
[Themes](https://wordpress.org/themes/twentytwentyfour/)
[Plugins](https://wordpress.org/plugins/thirstyaffiliates/)
[News](https://wordpress.org/news/2024/10/wordpress-community-creates-1000-block-themes-in-1000-days/)

**Comment by adamwoodnz** [comment]
> Almost all of our subnavs link back to home.
> 
> [Forums](https://wordpress.org/support/forum/installation/) [Developers](https://developer.wordpress.org/block-editor/) [Showcase](https://wordpress.org/showcase/nasa/) [Themes](https://wordpress.org/themes/twentytwentyfour/) [Plugins](https://wordpress.org/plugins/thirstyaffiliates/) [News](https://wordpress.org/news/2024/10/wordpress-community-creates-1000-block-themes-in-1000-days/)

True, but these blogs are like individual sites in my mind.

What I mean is, do most users enter from the Make home page, or do they go straight to the site they're contributing to? Is navigating to Make home a common route, or is it mostly for discovery coming from the global nav?

**Comment by jasmussen** [comment]
Entirely valid observation. For the moment the partial refresh Adam and I worked on was primarily CSS, on my end it wasn't clear how much bandwidth there was to additional improvements. To that end, Home breadcrumb or not, the current work in progress is a substantial improvement over what exists, so further improvements feel like they can wait if need be.

But if there's a neat path to a "Home" link, I'd echo the sentiment for consistency. It would also come with the benefit of a clearer understanding that "Make" is a network of sites, not a bunch of islands. 

To be mindful of, however, is how this gets done, especially on islands that have a lot of menu items, like [Core](https://make.wordpress.org/core/?new-theme=1). Want to make sure even with an added breadcrumb, there's room without overlap right up until it collapses to a dropdown. Coming to mind, we could rephrase a few things. Instead of `[icon] Make WordPress Core`, It could be `Make → [icon] Core`, or if need be, `Make → WordPress Core`. In this case, "Make" would be the breadcrumb home.

**Comment by fcoveram** [comment]
I'm drawn to keep the local nav as is for consistency, acknowledging that each make site has its page structure and that we could work on a particular nav bar for these sites.

**Comment by ryelle** [comment]
> What I mean is, do most users enter from the Make home page, or do they go straight to the site they're contributing to? Is navigating to Make home a common route, or is it mostly for discovery coming from the global nav?

I'll add that in all my time as a contributor, I very rarely go look at just make.w.org — IMO that's more of a landing page for new contributors, not something people are looking at often. There isn't a link back to the page now, and I've never missed it.

For a future iteration, what would be more useful is a way to skip directly between sites — like a dropdown nav somewhere, so that I can be on /core and switch over to /meta, or /accessibility, etc.

**Comment by StevenDufresne** [comment]
I'm okay with closing this.

**Comment by adamwoodnz** [comment]
Thanks all, let's keep things as is for now then.
