### ISSUE TITLE
Styling of tables in sticky posts could be improved

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wordpress.org#423]
See https://make.wordpress.org/core/2024/11/19/wordpress-6-7-1-release-schedule/

![Image](https://github.com/user-attachments/assets/c3d018e0-bcaa-44b6-9b84-9bbfe13aedaa)

@WordPress/meta-design what do you think, make the table body row backgrounds white? Or alternating white/light grey?

**Comment by jasmussen** [comment]
Short of refreshing the visual style of pinned posts, the easiest is to probably just add a white background to the table. 

Another option is to use CSS `currentColor` in an array of shades for the table itself, so that the colors better blend in to any background. For example, instead of a light gray background, use an opacity of `currentColor`, essentially semitransparent text color. You can do that like this:

`border-color: color-mix( in srgb, currentColor 50%, transparent )`

That adds a 50% transparent version of the text color applied to the table, which means it'll work against any background color. You could use that both for the outer borders, inner borders, and the shaded table head background; just need to adjust the percentage value. If you style the basic table first, and compare with a screenshot of the past version, you should be able to get opacity values that match the hardcoded grays.
