### ISSUE TITLE
Side paddings of main content area in Make site

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wordpress.org#430]
Left and right paddings of post area in Make blogs make the layout unbalanced due to differences in width with the gray line separating posts.

![Image](https://github.com/user-attachments/assets/cb61e47a-e18c-4d30-8310-f7b3f61a9c46)

We could remove the left and right paddings to improve the layout. 

Note: I noticed that from 640px to narrow viewports, the padding goes to zero and the area looks as expected.

**Comment by adamwoodnz** [comment]
This carries over from the old theme, and I think the intention is to align the content with the content in posts that have a background color, for example here's Core with a sticky post followed by a normal one:

<img src="https://github.com/user-attachments/assets/1681b8b9-4666-438a-85d6-a2efae0675e6" width="900">

What do you think, is this existing alignment important, or should we remove the padding on the normal post so that the content aligns the the background of the sticky post?

**Comment by fcoveram** [comment]
We can remove the padding. Most navigation flow happens with the white background.
